src/frontend/ServicesDeskUCAB/Controllers/TipoCargoController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text;
using Newtonsoft.Json;
using ServicesDeskUCAB.DTO;
using ServicesDeskUCAB.ResponseHandler;

namespace ServicesDeskUCAB.Controllers
{
    public class TipoCargoController : Controller
    {
        public async Task<IActionResult> GestionTipoCargo()
        {
            try
            {
                AplicationResponseHandler<List<TipoCargoDTO>> ApiResponseH = new AplicationResponseHandler<List<TipoCargoDTO>>();
                
                HttpClient clientTCargo = new HttpClient();
                    
                   var response = await clientTCargo.GetAsync("https://localhost:7198/TipoCargo/ConsultaTCargo/");

                    if(response.IsSuccessStatusCode)
                    {
                        var responseStream = await response.Content.ReadAsStringAsync();
                        ApiResponseH = JsonConvert.DeserializeObject<AplicationResponseHandler<List<TipoCargoDTO>>>(responseStream);
                    } else 
                    {
                        BadRequest();
                    }


                return View(ApiResponseH!.Data);
            }catch(Exception ex)
            {
                Console.WriteLine(ex.Message +" || "+ ex.StackTrace);
                throw new Exception(ex.Message, ex.InnerException);
            }
            
        }
        public IActionResult VentanaAgregarTipoCargo()
        {
            try
            {
                return View();
            }catch(Exception ex)
            {
                Console.WriteLine(ex.Message + " || "+ex.StackTrace);
                throw new Exception(ex.Message + " || "+ex.StackTrace, ex.InnerException);
            }
        }

        public async Task<IActionResult> AgregarTCargo(TipoCargoDTO tipoCargo)
        {
            try
            {
                tipoCargo.id = 0;
                HttpClient client = new HttpClient();
                var _client = await client.PostAsJsonAsync<TipoCargoDTO>("https://localhost:7198/TipoCargo/CreateTCargo/", tipoCargo);
                    return RedirectToAction("GestionTipoCargo");
                    
            }catch(Exception ex)
            {
                Console.WriteLine(ex.Message + " || "+ex.StackTrace);
                throw new Exception(ex.Message + " || "+ex.StackTrace, ex.InnerException);
            }            
        }

        public async Task<IActionResult> VentanaEditarTipoCargo(int id)
        {
            try
            {
                AplicationResponseHandler<TipoCargoDTO> ResponseTipoCargo = new AplicationResponseHandler<TipoCargoDTO>();
                var dto = new TipoCargoDTO();
                HttpClient client = new HttpClient();

                var response = await client.GetAsync("https://localhost:7198/TipoCargo/ConsultaTCargo/" + id.ToString());    

                if(response.IsSuccessStatusCode)
                {
                    var responseStream = await response.Content.ReadAsStringAsync();
                    ResponseTipoCargo = JsonConvert.DeserializeObject<AplicationResponseHandler<TipoCargoDTO>>(responseStream);
                    dto = ResponseTipoCargo!.Data;
                }
                return View(dto);
                
            }catch(Exception ex)
            {
                Console.WriteLine(ex.Message + " || "+ex.StackTrace);
                throw new (ex.Message, ex);
            }
        }
        public async Task<IActionResult> ActualizarTCargo(TipoCargoDTO tipoCargo)
        {
            try
            {
              HttpClient client = new HttpClient();
              var _client = await client.PutAsJsonAsync("https://localhost:7198/TipoCargo/ActualizarTCargo/",tipoCargo);      

              return RedirectToAction("GestionTipoCargo");      
            }catch(Exception ex)
            {
                Console.WriteLine(ex.Message + " || "+ex.StackTrace);
                throw new (ex.Message + " || "+ex.StackTrace, ex.InnerException);
            }
        }

        public async Task<IActionResult> VentanaEliminarTipoCargo(int id)
        {
            try
            {
                return View(id);
                
            }catch(Exception ex)
            {
                Console.WriteLine(ex.Message + " || "+ex.StackTrace);
                throw new Exception(ex.Message, ex);
            }
        }
        public async Task<IActionResult> EliminarTCargo(int id)
        {
            try
            {
                HttpClient client = new HttpClient();
                var _client = await client.DeleteAsync("https://localhost:7198/TipoCargo/EliminarTCargo/"+id.ToString());
                return RedirectToAction("GestionTipoCargo");
            }catch(Exception ex)
            {
                Console.WriteLine(ex.Message + " || "+ex.StackTrace);
                throw new Exception(ex.Message + " || "+ex.StackTrace, ex.InnerException);
            }
        }
    }
}

src/frontend/ServicesDeskUCAB/Views/TipoCargo/GestionTipoCargo.cshtml
@model List<ServicesDeskUCAB.DTO.TipoCargoDTO>

@section scripts{
    <script>
        $(function () {
            var PlaceHolderElement = $('#PlaceHolderTipoCargo');
            $('#btnAgregarTc').click(function (event) {
                var url = $(this).data('url');
                $.get(url).done(function (data) {
                    PlaceHolderElement.html(data);
                    PlaceHolderElement.find('header').empty();
                    PlaceHolderElement.find('footer').empty();
                    PlaceHolderElement.find('.modal').modal('show');
                })
            })

        })
    </script>

@* Js para traer la ventana emergente de confirmacion de eliminacion *@
    <script>
       $(function () {
            var PlaceHolderElement = $('#PlaceHolderEliminar');
            $("#btnEliminarTc, .btn-danger").click(function (event) {
                var id = $(this).closest('tr').find('.id').text();
                var url = $(this).data('url').replace("idTipoCargo", id);
                $.get(url).done(function (data) {
                    PlaceHolderElement.html(data);
                    PlaceHolderElement.find('header').empty();
                    PlaceHolderElement.find('footer').empty();
                    PlaceHolderElement.find('.modal').modal('show');
                })
            })

        })
    </script>


        @* Js para traer la ventana emergente de edicion de Tipo Cargo *@
    <script>
        $(function () {
            var PlaceHolderElement = $('#PlaceHolderEditar');
            $("#btnEditarTc, .btn-primary").click(function (event) {
                var id = $(this).closest('tr').find('.id').text();
                var url = $(this).data('url').replace("idTipoCargo", id);
                $.get(url).done(function (data) {
                    PlaceHolderElement.html(data);
                    PlaceHolderElement.find('header').empty();
                    PlaceHolderElement.find('footer').empty();
                    PlaceHolderElement.find('.modal').modal('show');
                })
            })

        })
    </script>

}
@{
        ViewData["Title"] = "Gestion Tipo de Cargo";
}


    <div id="PlaceHolderTipoCargo"></div>
    <div id="PlaceHolderEliminar"></div>
    <div id="PlaceHolderEditar"></div>

    @* Boton para abrir el modal*@
    <button id=btnAgregarTc type="button" class="btn btn-warning btn-sm" data-toggle="ajax-modal" data-target="#UpAgregar" data-url="@Url.Action("VentanaAgregarTipoCargo")">
        Crear Tipo de Cargo
    </button>
    <br />
    <br/>

    <table class="table">
    <tr>
        <th>
            Id
        </th>
        <th>
            Tipo de Cargo
        </th>
        <th>
            Acciones
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td class="id">
                @Html.DisplayFor(i => item.id)
            </td>
            <td>
                @Html.DisplayFor(i => item.nombre)
            </td>
            <td>
                <button id=btnEditarTc type="button" class="btn btn-primary btn-sm" data-toggle="ajax-modal" data-target="#popUpEditar" data-url="@Url.Action("VentanaEditarTipoCargo","TipoCargo",new {id = "idTipoCargo"})">
                    Editar
                </button>
                <button id=btnEliminarTc type="button" class="btn btn-danger btn-sm" data-toggle="ajax-modal" data-target="#popUpEliminar" data-url="@Url.Action("VentanaEliminarTipoCargo","TipoCargo",new {id = "idTipoCargo"})">
                        Eliminar
                </button>
            </td>
        </tr>
    }

</table>

src/frontend/ServicesDeskUCAB/Views/TipoCargo/VentanaAgregarTipoCargo.cshtml
@model ServicesDeskUCAB.DTO.TipoCargoDTO
@{
    ViewData["Title"] = "Gestion Tipo de Cargo";
}
<!-- IMPORTACIONES DE LIBRERIAS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>

<!-- VENTANA EMERGENTE "MODAL" -->
<div class="modal fade" id="UpAgregar" tabindex="-1" role="dialog" aria-labelledby="UpAgregarTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Agregar Tipo de Cargo</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close" onclick="location.href='@Url.Action("GestionTipoCargo", "TipoCargo")'">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @using (Html.BeginForm("AgregarTCargo", "TipoCargo", FormMethod.Post))
            {
                <div class="modal-body">
                    <span>Tipo de Cargo: </span> @Html.TextBoxFor(m => m.nombre)
                    @Html.ValidationMessageFor(m => m.nombre ,null, new { @class = "text-danger" })
                    <br />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="location.href='@Url.Action("GestionTipoCargo", "TipoCargo")'">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Crear</button>
                </div>
            }
        </div>
    </div>
</div>

src/frontend/ServicesDeskUCAB/Views/TipoCargo/VentanaEditarTipoCargo.cshtml
@model ServicesDeskUCAB.DTO.TipoCargoDTO
@section scripts{
}

@{
    ViewData["Title"] = "Gestion Tipo de Cargo";
}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>

<div class="modal fade" id="popUpEditar" tabindex="-1" role="dialog" aria-labelledby="popUpEditarTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Editar Tipo de Cargo</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close"onclick="location.href='@Url.Action("GestionTipoCargo", "TipoCargo")'">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @using (Html.BeginForm("ActualizarTCargo", "TipoCargo", FormMethod.Post))
            {
                <div class="modal-body">
                    @Html.TextBoxFor(m => m.id, new { @Value = Model.id, @type="hidden"})
                    <span>Tipo de Cargo: </span> @Html.TextBoxFor(m => m.nombre, new { @Value = Model.nombre})
                    @Html.ValidationMessageFor(m => m.nombre ,null, new { @class = "text-danger" })
                    <br />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="location.href='@Url.Action("GestionTipoCargo", "TipoCargo")'">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Editar</button>
                </div>
            }
        </div>
    </div>
</div>

src/frontend/ServicesDeskUCAB/Views/TipoCargo/VentanaEliminarTipoCargo.cshtml
@model int
@{
    ViewData["Title"] = "Gestion Tipo de Cargo";
}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />


<!-- VENTANA EMERGENTE "MODAL" -->
<div class="modal fade" id="popUpEliminar" tabindex="-1" role="dialog" aria-labelledby="popUpEliminarTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Eliminar Tipo de Cargo</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close" onclick="location.href='@Url.Action("GestionTipoCargo", "TipoCargo")'">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
                <div class="modal-body">
                    ¿Está seguro de que desea eliminar el Tipo de Cargo seleccionado?
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="location.href='@Url.Action("GestionTipoCargo", "TipoCargo")'">Cancelar</button>
                    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("EliminarTCargo","TipoCargo",new {id = Model})'">Aceptar</button>
                </div>
        </div>
    </div>
</div>