src/frontend/ServicesDeskUCAB/Controllers/ModeloJerarquicoController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ServicesDeskUCAB.DTO;
using System.Dynamic;
using System.Text;
using ServicesDeskUCAB.Factory;
using ServicesDeskUCAB.ResponseHandler;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServicesDeskUCAB.Controllers
{
    public class ModeloJerarquicoController : Controller
    {
        public async Task<IActionResult> GestionMJerarquico()
        {
            try
            {
                AplicationResponseHandler<List<ModeloJCDTO>> apiResponseH = new AplicationResponseHandler<List<ModeloJCDTO>>();
                
                using(var clientMJerarquico = FactoryHttp.CreateClient())
                {
                       var ModeloJ = await clientMJerarquico.GetAsync("https://localhost:7198/ModeloAprobacion/GetModeloJerarquico/");

                        var response = await ModeloJ.Content.ReadAsStringAsync();

                        apiResponseH = JsonConvert.DeserializeObject<AplicationResponseHandler<List<ModeloJCDTO>>>(response);

                    return View(apiResponseH.Data);
                }  
            }catch(Exception ex)
            {
                Console.WriteLine(ex.Message +" || "+ ex.StackTrace);
                throw new Exception(ex.Message, ex.InnerException);
            }
        }

        public async Task<IActionResult> VentanaAgregarModeloJerarquico()
        {
            try
            {
                AplicationResponseHandler<List<CategoriaDTO>> ApiResponse = new AplicationResponseHandler<List<CategoriaDTO>>();

                List<CategoriaDTO> categorias = new List<CategoriaDTO>();
                   
                using(var clientMJ = FactoryHttp.CreateClient())
                {
                   var categoria = await clientMJ.GetAsync("https://localhost:7198/Categoria/ConsultaCategorias");

                        string response = await categoria.Content.ReadAsStringAsync();

                       ApiResponse = JsonConvert.DeserializeObject<AplicationResponseHandler<List<CategoriaDTO>>>(value: response);

                        dynamic model = new ExpandoObject();
                        model.Categorias = ApiResponse!.Data;

                        return View(model);
                    
                }
            }catch(Exception ex)
            {
                throw new (ex.Message + " || "+ex.StackTrace, ex);
            }
        } 

        public async Task<IActionResult> AgregarMJerarquico(ModeloJIDTO modeloJerarquico)
        {
            try
            {
                modeloJerarquico.id = 0;
               var client = FactoryHttp.CreateClient();

               var _client = await client.PostAsJsonAsync<ModeloJIDTO>("https://localhost:7198/ModeloAprobacion/Jerarquico/", modeloJerarquico);

                return RedirectToAction("GestionMJerarquico");
            }catch(Exception ex)
            {
                throw new Exception(ex.Message + " || "+ex.StackTrace, ex.InnerException);
            }
        }

        public async Task<IActionResult> VentanaEditarModeloJerarquico(int id)
        {
            try
            {
                AplicationResponseHandler<ModeloJerarquicoDTO> ApiResponseH = new AplicationResponseHandler<ModeloJerarquicoDTO>();
                AplicationResponseHandler<List<CategoriaDTO>> apiCategoria = new AplicationResponseHandler<List<CategoriaDTO>>();
                
                using(var client = FactoryHttp.CreateClient())
                {
                    var response = await client.GetAsync("https://localhost:7198/ModeloAprobacion/Jerarquico/" + id.ToString());
                    var responseStream = await response.Content.ReadAsStringAsync();
                    ApiResponseH = JsonConvert.DeserializeObject<AplicationResponseHandler<ModeloJerarquicoDTO>>(responseStream);
                   
                    var categoria = await client.GetAsync("https://localhost:7198/Categoria/ConsultaCategorias");
        
                    string response2 = await categoria.Content.ReadAsStringAsync();
        
                    apiCategoria = JsonConvert.DeserializeObject<AplicationResponseHandler<List<CategoriaDTO>>>(value: response2);
        
                    List<SelectListItem> listItemsCategoria = crearCategoriaDropDown(apiCategoria!.Data);

                    var tupla = new Tuple<ModeloJerarquicoDTO,List<SelectListItem>>(ApiResponseH!.Data, listItemsCategoria);

                    return View(tupla);
                }

            }catch(Exception ex)
            {
                throw new Exception(ex.Message + " || "+ ex.StackTrace, ex);
            }
        }

        private static List<SelectListItem> crearCategoriaDropDown(List<CategoriaDTO> lista)
        {
            List<SelectListItem> listItems = new List<SelectListItem>();

            foreach (var item in lista)
            {
                listItems.Add(new SelectListItem
                {
                    Text = item.nombre,
                    Value = item.id.ToString(),
                });
            }

            return listItems;
        }


        public async Task<IActionResult> ActualizarModeloJerarquico([Bind(Prefix ="Item1")] ModeloJerarquicoDTO modeloJerarquico)
        {
            try
            {
                
                    var client = FactoryHttp.CreateClient();
                    var _client = await client.PutAsJsonAsync<ModeloJerarquicoDTO>("https://localhost:7198/ModeloAprobacion/ActualizaModeloJerarquico/", modeloJerarquico);

                    return RedirectToAction("GestionMJerarquico");
            }catch(Exception ex)
            {
                throw new Exception(ex.Message+""+ex.StackTrace, ex);
            }
        }

        public async Task<IActionResult> VentanaEliminarModeloJerarquico(int id)
        {
            try
            {
                return View(id);
            }catch(Exception ex)
            {
                throw new Exception(ex.Message + " || "+ex.StackTrace, ex.InnerException);
            }
        }      

        public async Task<IActionResult> EliminarMJerarquico(int id)
        {
            try
            {
                var client = FactoryHttp.CreateClient();
                var _client = await client.DeleteAsync("https://localhost:7198/ModeloAprobacion/DeleteModeloJerarquico/"+id.ToString());

                return RedirectToAction("GestionMJerarquico");
                
            }catch(Exception ex)
            {
                throw new Exception(ex.Message + " || "+ex.StackTrace, ex.InnerException);
            }
        }


    }
}

src/frontend/ServicesDeskUCAB/Views/ModeloJerarquico/GestionMJerarquico.cshtml
@model List<ServicesDeskUCAB.DTO.ModeloJCDTO>
@section scripts
{
    <script>
        $(function () {
            var PlaceHolderElement = $('#PlaceHolderMJerarquico');
            $('#btnAgregarMJ').click(function (event) {
                var url = $(this).data('url');
                $.get(url).done(function (data) {
                    PlaceHolderElement.html(data);
                    PlaceHolderElement.find('header').empty();
                    PlaceHolderElement.find('footer').empty();
                    PlaceHolderElement.find('.modal').modal('show');
                })
            })

        })
    </script>    

    <script>
       $(function () {
            var PlaceHolderElement = $('#PlaceHolderEliminar');
            $("#btnMjEliminar, .btn-danger").click(function (event) {
                var id = $(this).closest('tr').find('.id').text();
                var url = $(this).data('url').replace("idModeloJerarquico", id);
                $.get(url).done(function (data) {
                    PlaceHolderElement.html(data);
                    PlaceHolderElement.find('header').empty();
                    PlaceHolderElement.find('footer').empty();
                    PlaceHolderElement.find('.modal').modal('show');
                })
            })

        })
    </script>

    <script>
        $(function () {
            var PlaceHolderElement = $('#PlaceHolderEditar');
            $("#btnMjEditar, .btn-primary").click(function (event) {
                var id = $(this).closest('tr').find('.id').text();
                var url = $(this).data('url').replace("idModeloJerarquico", id);
                $.get(url).done(function (data) {
                    PlaceHolderElement.html(data);
                    PlaceHolderElement.find('header').empty();
                    PlaceHolderElement.find('footer').empty();
                    PlaceHolderElement.find('.modal').modal('show');
                })
            })

        })
    </script>
}

@{
        ViewData["Title"] = "Gestion Modelo Jerarquico";
}  
    <div id="PlaceHolderMJerarquico"></div>
    <div id="PlaceHolderEliminar"></div>
    <div id="PlaceHolderEditar"></div>

    @* Boton para abrir el modal*@
    <button id=btnAgregarMJ type="button" class="btn btn-warning btn-sm" data-toggle="ajax-modal" data-target="#UpAgregar" data-url="@Url.Action("VentanaAgregarModeloJerarquico")">
        Crear Modelo Jerarquico
    </button>
    <br />
    <br/>

<table class="table">
    <tr>
        <th>
            Listado
        </th>
        <th>
            Modelo Jerarquico
        </th>
        <th>
            categoria
        </th>
        <th>
            Acciones
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td class="id">
                @Html.DisplayFor(i => item.id)
            </td>
            <td>
                @Html.DisplayFor(i => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(i => item.nombreCategoria)
            </td>
            <td>
                <button id=btnMjEditar type="button" class="btn btn-primary btn-sm" data-toggle="ajax-modal" data-target="#popUpEditar" data-url="@Url.Action("VentanaEditarModeloJerarquico","ModeloJerarquico",new {id = "idModeloJerarquico"})">
                    Editar
                </button>
                <button id=btnMjEliminar type="button" class="btn btn-danger btn-sm" data-toggle="ajax-modal" data-target="#popUpEliminar" data-url="@Url.Action("VentanaEliminarModeloJerarquico","ModeloJerarquico",new {id = "idModeloJerarquico"})">
                        Eliminar
                </button>
            </td>
        </tr>
    }

</table>    

src/frontend/ServicesDeskUCAB/Views/ModeloJerarquico/VentanaEliminarModeloJerarquico.cshtml
@model int
@{
    ViewData["Title"] = "Eliminar Modelo Jerarquico";
}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />

<div class="modal fade" id="popUpEliminar" tabindex="-1" role="dialog" aria-labelledby="popUpEliminarTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Eliminar Modelo Jerarquico</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close" onclick="location.href='@Url.Action("GestionMJerarquico", "ModeloJerarquico")'">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
                <div class="modal-body">
                    ¿Está seguro de que desea eliminar el Modelo Jerarquico seleccionado?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="location.href='@Url.Action("GestionMJerarquico", "ModeloJerarquico")'">Cancelar</button>
                    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("EliminarMJerarquico", "ModeloJerarquico",new {id = Model})'">Aceptar</button>
                </div>
        </div>
    </div>
</div>