src/frontend/ServicesDeskUCAB/Controllers/JerarquicoTipoCargoController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ServicesDeskUCAB.DTO;
using System.Dynamic;
using System.Text;
using ServicesDeskUCAB.Factory;
using ServicesDeskUCAB.ResponseHandler;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServicesDeskUCAB.Controllers
{
    public class JerarquicoTipoCargoController : Controller
    {
        public async Task<IActionResult> GestionJerarquicoTCargo()
        {
            try
            {
                    AplicationResponseHandler<List<JerarquicoTCargoCDTO>> jResponse = new AplicationResponseHandler<List<JerarquicoTCargoCDTO>>();
                    HttpClient JClient = FactoryHttp.CreateClient();
                    
                    var response = await JClient.GetAsync("https://localhost:7198/JerarquicoTipoCargo/ListJerarquicoTCargo/");

                        if(response.IsSuccessStatusCode)
                        {
                            var responseStream = await response.Content.ReadAsStringAsync();
                            jResponse = JsonConvert.DeserializeObject<AplicationResponseHandler<List<JerarquicoTCargoCDTO>>>(responseStream);

                        }
                    return View(jResponse.Data);

            }catch(Exception ex)
            {
                throw new Exception(ex.Message, ex);
            }
        }

        public async Task<IActionResult> VentanaAgregarJerarquicoTCargo()
        {
            try
            {
                AplicationResponseHandler<List<TipoCargoDTO>> ApiResponseH = new AplicationResponseHandler<List<TipoCargoDTO>>();
                AplicationResponseHandler<List<ModeloJerarquicoDTO>> mjResponse = new AplicationResponseHandler<List<ModeloJerarquicoDTO>>();

                using(var mjClient = FactoryHttp.CreateClient())
                {
                        var mJerarquico = await mjClient.GetAsync("https://localhost:7198/ModeloAprobacion/GetModeloJerarquico/");
                        var tCargo      = await mjClient.GetAsync("https://localhost:7198/TipoCargo/ConsultaTCargo/");

                        string response = await mJerarquico.Content.ReadAsStringAsync();
                        string response2 = await tCargo.Content.ReadAsStringAsync();

                        ApiResponseH = JsonConvert.DeserializeObject<AplicationResponseHandler<List<TipoCargoDTO>>>(response2);
                        mjResponse = JsonConvert.DeserializeObject<AplicationResponseHandler<List<ModeloJerarquicoDTO>>>(response);

                        dynamic model = new ExpandoObject();
                        model.TipoCargo = ApiResponseH.Data;
                        model.ModeloJerarquico = mjResponse.Data;

                        return View(model);
                }

            }catch(Exception ex)
            {
                throw new Exception(ex.Message, ex);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AgregarJerarquicoTCargo(JerarquicoTipoCargoDTO dto)
        {
            try{
                    dto.id = 0;
                    var client = FactoryHttp.CreateClient();

                    var _client = await client.PostAsJsonAsync<JerarquicoTipoCargoDTO>("https://localhost:7198/JerarquicoTipoCargo/JerarquicoTCargo/",dto);

                    return RedirectToAction("GestionJerarquicoTCargo");
            }catch(Exception ex)
            {
                throw new Exception(ex.Message, ex);
            }
        }

        public async Task<IActionResult> VentanaEditarJerarquicoTCargo(int id)
        {
            try
            {
                AplicationResponseHandler<JerarquicoTipoCargoDTO> jcResponse = new AplicationResponseHandler<JerarquicoTipoCargoDTO>();
                AplicationResponseHandler<List<TipoCargoDTO>> tcResponse = new AplicationResponseHandler<List<TipoCargoDTO>>();
                AplicationResponseHandler<List<ModeloJCDTO>> mjcResponse = new AplicationResponseHandler<List<ModeloJCDTO>>();

                using(var client = FactoryHttp.CreateClient())
                {
                    var response1 = await client.GetAsync("https://localhost:7198/JerarquicoTipoCargo/JerarquicoTCargo/" + id.ToString());
                    var respStream = await response1.Content.ReadAsStringAsync();

                    var response2 = await client.GetAsync("https://localhost:7198/TipoCargo/ConsultaTCargo/");
                    var resptcargo = await response2.Content.ReadAsStringAsync();

                    var response3 = await client.GetAsync("https://localhost:7198/ModeloAprobacion/GetModeloJerarquico/");
                    var resModelo = await response3.Content.ReadAsStringAsync();

                    jcResponse = JsonConvert.DeserializeObject<AplicationResponseHandler<JerarquicoTipoCargoDTO>>(respStream);
                    tcResponse = JsonConvert.DeserializeObject<AplicationResponseHandler<List<TipoCargoDTO>>>(resptcargo);
                    mjcResponse = JsonConvert.DeserializeObject<AplicationResponseHandler<List<ModeloJCDTO>>>(resModelo);

                    List<SelectListItem> listItemsTCargo = crearTipoCargoDropDown(tcResponse.Data);
                    List<SelectListItem> listModelJ = crearModeloJerarquicoDropDown(mjcResponse.Data);
                    var tuple = new Tuple<JerarquicoTipoCargoDTO, List<SelectListItem>, List<SelectListItem>>(jcResponse.Data, listItemsTCargo, listModelJ);
                    return View(tuple);
                }

            }catch(Exception ex)
            {
                throw new Exception(ex.Message, ex);
            }
        }

        public async Task<IActionResult> ActualizarJerarquicoTCargo(JerarquicoTipoCargoDTO jtcDto)
        {
            try
            {
                var client = FactoryHttp.CreateClient();
                var _client = await client.PutAsJsonAsync<JerarquicoTipoCargoDTO>("https://localhost:7198/JerarquicoTipoCargo/UpdateJerarquicoTC/", jtcDto);

                return RedirectToAction("GestionJerarquicoTCargo");
            }catch(Exception ex)
            {
                throw new Exception(ex.Message, ex);
            }
        }

        public async Task<IActionResult> VentanaEliminarJerarquicoTCargo(int id)
        {
            try
            {
                return View(id);
            }catch(Exception ex)
            {
                throw new Exception(ex.Message, ex);
            }
        }

        public async Task<IActionResult> EliminarJerarquicoTCargo(int id)
        {
            try
            {
                var client = FactoryHttp.CreateClient();
                var _client = await client.DeleteAsync("https://localhost:7198/JerarquicoTipoCargo/DeleteJerarquicoTC/"+id.ToString());                

                return RedirectToAction("GestionJerarquicoTCargo");


            }catch(Exception ex)
            {
                throw new Exception(ex.Message, ex);
            }
        }

        private static List<SelectListItem> crearTipoCargoDropDown(List<TipoCargoDTO> lista)
        {
            List<SelectListItem> listItems = new List<SelectListItem>();

            foreach (var item in lista)
            {
                listItems.Add(new SelectListItem
                {
                    Text = item.nombre,
                    Value = item.id.ToString(),
                });
            }

            return listItems;
        }

        private static List<SelectListItem> crearModeloJerarquicoDropDown(List<ModeloJCDTO> lista)
        {
            List<SelectListItem> listItems = new List<SelectListItem>();

            foreach (var item in lista)
            {
                listItems.Add(new SelectListItem
                {
                    Text = item.Nombre,
                    Value = item.id.ToString(),
                });
            }

            return listItems;
        }

    }
}

src/frontend/ServicesDeskUCAB/Views/JerarquicoTipoCargo/GestionJerarquicoTCargo.cshtml
@model List<ServicesDeskUCAB.DTO.JerarquicoTCargoCDTO>
@section scripts
{
    <script>
        $(function () {
            var PlaceHolderElement = $('#PlaceHolderJerarquicoTC');
            $('#btnAgregarJTC').click(function (event) {
                var url = $(this).data('url');
                $.get(url).done(function (data) {
                    PlaceHolderElement.html(data);
                    PlaceHolderElement.find('header').empty();
                    PlaceHolderElement.find('footer').empty();
                    PlaceHolderElement.find('.modal').modal('show');
                })
            })

        })
    </script> 


    <script>
       $(function () {
            var PlaceHolderElement = $('#PlaceHolderJTCEliminar');
            $("#btnEliminarJTC, .btn-danger").click(function (event) {
                var id = $(this).closest('tr').find('.id').text();
                var url = $(this).data('url').replace("idJerarquicoTc", id);
                $.get(url).done(function (data) {
                    PlaceHolderElement.html(data);
                    PlaceHolderElement.find('header').empty();
                    PlaceHolderElement.find('footer').empty();
                    PlaceHolderElement.find('.modal').modal('show');
                })
            })

        })
    </script>

        <script>
        $(function () {
            var PlaceHolderElement = $('#PlaceHolderJTCEditar');
            $("#btnEditarJTC, .btn-primary").click(function (event) {
                var id = $(this).closest('tr').find('.id').text();
                var url = $(this).data('url').replace("idJerarquicoTc", id);
                $.get(url).done(function (data) {
                    PlaceHolderElement.html(data);
                    PlaceHolderElement.find('header').empty();
                    PlaceHolderElement.find('footer').empty();
                    PlaceHolderElement.find('.modal').modal('show');
                })
            })

        })
    </script>

}

@{
    ViewData["Title"] = "Gestion Jerarquico Tipo Cargo";
}

<div id="PlaceHolderJerarquicoTC"></div>
<div id="PlaceHolderJTCEliminar"></div>
<div id="PlaceHolderJTCEditar"></div>

<button id="btnAgregarJTC" type="button" class="btn btn-warning btn-sm" data-toggle="ajax-modal" data-target="#UpAgregar" data-url="@Url.Action("VentanaAgregarJerarquicoTCargo")">
        Crear Jerarquico Tipo Cargo
</button>

<table class="table">
    <tr>
        <th>listado</th>
        <th>Orden</th>
        <th>Tipo de Cargo</th>
        <th>Modelo Jerarquico</th>
        <th>Acciones</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
           <td class="id">
                @Html.DisplayFor(i => item.id)
           </td>
           <td>
                @Html.DisplayFor(i => item.orden)
           </td> 
           <td>
                @Html.DisplayFor(i => item.tipocargo)
           </td>
           <td>
                @Html.DisplayFor(i => item.modelo)
           </td>
           <td>
            <button id="btnEditarJTC" type="button" class="btn btn-primary btn-sm" data-toggle="ajax-modal" data-target="#popUpEditar" data-url="@Url.Action("VentanaEditarJerarquicoTCargo","JerarquicoTipoCargo",new {id = "idJerarquicoTc"})">
                Editar
            </button>
            <button id="btnEliminarJTC" type="button" class="btn btn-danger btn-sm" data-toggle="ajax-modal" data-target="#popUpEliminar" data-url="@Url.Action("VentanaEliminarJerarquicoTCargo","JerarquicoTipoCargo",new {id = "idJerarquicoTc"})">
                Eliminar
            </button>
           </td>
        </tr>
    }
</table>

src/frontend/ServicesDeskUCAB/Views/JerarquicoTipoCargo/VentanaAgregarJerarquicoTCargo.cshtml
@model dynamic
@using ServicesDeskUCAB.DTO
@{
    ViewData["Title"] = "Agregar Jerarquico Tipo Cargo";
}

<!-- IMPORTACIONES DE LIBRERIAS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>


<div class="modal fade" id="UpAgregar" tabindex="-1" role="dialog" aria-labelledby="UpAgregarTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
               <h5 class="modal-title" id="exampleModalLongTitle">Agregar Jerarquico Tipo Cargo</h5> 
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close" onclick="location.href='@Url.Action("GestionJerarquicoTCargo", "JerarquicoTipoCargo")'">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
<form asp-action="AgregarJerarquicoTCargo" method="post">
                <div class="modal-body">
                
                <div class="form-group">
                        <label>Orden de Aprobacion</label>
                        <input type="numeric" name="orden" class="form-control" placeholder="Orden de Aprobacion">
                </div>
                                
                <div class="form-group">
                    <label for="categoria">modelo Jerarquico</label>
                    <select class="form-control" id="modeloJerarquico" name="modelojerarquicoid">
                        @foreach (ModeloJerarquicoDTO c in Model.ModeloJerarquico)
                        {
                            <option value="@c.id">@c.nombre</option>
                        }
                    </select>
                </div>

                <div class="form-group">
                    <label for="tipocargo"> Tipo Cargo</label>
                    <select class="form-control" id="tipocargo" name="tipocargoid">
                        @foreach (TipoCargoDTO tc in Model.TipoCargo)
                        {
                            <option value="@tc.id">@tc.nombre</option>
                        }
                    </select>
                </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="location.href='@Url.Action("GestionJerarquicoTCargo", "JerarquicoTipoCargo")'">Cancelar</button>
                    <button type="submit" class="btn btn-success">Crear</button>
                </div>
            </form>            
        </div>
    </div>
</div>

src/frontend/ServicesDeskUCAB/Views/JerarquicoTipoCargo/VentanaEditarJerarquicoTCargo.cshtml
@using ServicesDeskUCAB.DTO
@model Tuple<JerarquicoTipoCargoDTO, List<SelectListItem>, List<SelectListItem>>
@{
    ViewData["Title"] = "Editar Jerarquico Tipo Cargo";
}    

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>

<div class="modal fade" id="popUpEditar" tabindex="-1" role="dialog" aria-labelledby="popUpEditarTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Editar Jerarquico Tipo Cargo</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close"onclick="location.href='@Url.Action("GestionJerarquicoTCargo", "JerarquicoTipoCargo")'">
                    <span aria-hidden="true">&times;</span>
                </button>            
        </div>
        @using(Html.BeginForm("ActualizarJerarquicoTCargo","JerarquicoTipoCargo", FormMethod.Post))
        {
            <div class="modal-body">
                    <div class="form-group">
                        @Html.TextBoxFor(j=> j.Item1.id, new { @Class = Model.Item1.id, @Type ="hidden"})
                       <span>Orden de Aprobacion: </span> @Html.TextBoxFor(j => j.Item1.orden, new { @Value = Model.Item1.orden, @Class = "form-control"})
                       @Html.ValidationMessageFor(j => j.Item1.orden, null, new { @Class = "text-danger"})
                    </div>
                    <div class="form-group">
                        <span>Tipo Cargo</span> @Html.DropDownListFor(j => j.Item1.tipoCargoid, Model.Item2,"Seleccione Tipo Cargo", new{ @Class = "form-select"})
                        @Html.ValidationMessageFor(j => j.Item1.tipoCargoid, null, new{ @Class = "text-danger"})
                    </div>
                    <div class="form-group">
                         <span>Modelo Jerarquico</span>@Html.DropDownListFor(j => j.Item1.modelojerarquicoid, Model.Item3, "Seleccione el Modelo", new { @Class = "form-select"})
                         @Html.ValidationMessageFor(j => j.Item1.modelojerarquicoid, null, new{ @Class = "text-danger"})   
                    </div>  
            </div>
            <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="location.href='@Url.Action("GestionJerarquicoTCargo", "JerarquicoTipoCargo")'">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Editar</button>                
            </div>
        }
    </div>
</div>

src/frontend/ServicesDeskUCAB/Views/JerarquicoTipoCargo/VentanaEliminarJerarquicoTCargo.cshtml
@model int
@{
    ViewData["Title"] = "Eliminar Jerarquico Tipo Cargo";
}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />

<div class="modal fade" id="popUpEliminar" tabindex="-1" role="dialog" aria-labelledby="popUpEliminarTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
       <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Eliminar Jerarquico Tipo Cargo</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close" onclick="location.href='@Url.Action("GestionJerarquicoTCargo", "JerarquicoTipoCargo")'">
                    <span aria-hidden="true">&times;</span>
                </button>   
        </div>
        <div class="modal-body">
                    ¿Está seguro de que desea eliminar el Jerarquico Tipo Cargo seleccionado?
        </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="location.href='@Url.Action("GestionJerarquicoTCargo", "JerarquicoTipoCargo")'">Cancelar</button>
                    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("EliminarJerarquicoTCargo", "JerarquicoTipoCargo",new {id = Model})'">Aceptar</button>
                </div>        
       </div> 
    </div>
</div>