src/frontend/ServicesDeskUCAB/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System;
using ServicesDeskUCAB.DTO;
using ServicesDeskUCAB.Models;
using System.Reflection;
using ServicesDeskUCAB.ResponseHandler;
using Newtonsoft.Json;


namespace ServicesDeskUCAB.Controllers
{
    public class CategoriaController : Controller
    {
        public async Task<IActionResult> GestionCategorias()
        {
            try
            {
                AplicationResponseHandler<List<CategoriaDTO>> apiResponse = new AplicationResponseHandler<List<CategoriaDTO>>();
                HttpClient client = new HttpClient();
                var response = await client.GetAsync("https://localhost:7198/Categoria/ConsultaCategorias");
                if (response.IsSuccessStatusCode)
                {
                    var responseString = await response.Content.ReadAsStringAsync();
                    apiResponse = JsonConvert.DeserializeObject<AplicationResponseHandler<List<CategoriaDTO>>>(responseString);
                }
                return View(apiResponse.Data);
            }
            catch (Exception ex)
            {
                throw ex.InnerException!;
            }
        }

        public IActionResult VentanaAgregarCategoria()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                throw ex.InnerException!;
            }
        }

        public async Task<IActionResult> AgregarCategoria(CategoriaDTO categoria)
        {
            try
            {
                HttpClient client = new HttpClient();
                StringContent content = new StringContent(JsonConvert.SerializeObject(categoria), Encoding.UTF8, "application/json");
                var response = await client.PostAsync("https://localhost:7198/Categoria/CreateCategoria", content);
                return RedirectToAction("GestionCategorias");
            }
            catch (Exception ex)
            {
                throw ex.InnerException!;
            }
        }

        public IActionResult VentanaEliminarCategoria(int id)
        {
            try
            {
                return View(id);
            }
            catch (Exception ex)
            {
                throw ex.InnerException!;
            }
        }

        public async Task<IActionResult> EliminarCategoria(int id)
        {
            try
            {
                HttpClient client = new HttpClient();
                var _client = await client.DeleteAsync("https://localhost:7198/Categoria/Eliminar/" + id.ToString());
                return RedirectToAction("GestionCategorias");
            }
            catch (Exception ex)
            {
                throw ex.InnerException!;
            }
        }

        public async Task<IActionResult> VentanaEditarCategoria(int id)
        {
            try
            {
                AplicationResponseHandler<CategoriaDTO> apiResponse = new AplicationResponseHandler<CategoriaDTO>();
                HttpClient client = new HttpClient();
                var response = await client.GetAsync("https://localhost:7198/Categoria/ConsultaCategoria/" + id.ToString());
                if (response.IsSuccessStatusCode)
                {
                    var responseString = await response.Content.ReadAsStringAsync();
                    apiResponse = JsonConvert.DeserializeObject <AplicationResponseHandler<CategoriaDTO>>(responseString);
                }
                return View(apiResponse.Data);
            }
            catch (Exception ex)
            {
                throw ex.InnerException!;
            }
        }

        public async Task<IActionResult> EditarCategoria(CategoriaDTO categoria)
        {
            try
            {
                HttpClient client = new HttpClient();
                var _client = await client.PutAsJsonAsync("https://localhost:7198/Categoria/Actualizar", categoria);
                return RedirectToAction("GestionCategorias");
            }
            catch (Exception ex)
            {
                throw ex.InnerException!;
            }
        }
    }
}

src/frontend/ServicesDeskUCAB/Views/Categoria/GestionCategorias.cshtml
@model List<ServicesDeskUCAB.DTO.CategoriaDTO>


@section scripts{

    <!-- JS PARA TRAER LA VENTANA EMERGENTE DEL BOTON "CREAR PRIORIDAD" -->
    <script>
        $(function () {
            var PlaceHolderElement = $('#PlaceHolderCategoria');
            $('#btnAgregar').click(function (event) {
                var url = $(this).data('url');
                $.get(url).done(function (data) {
                    PlaceHolderElement.html(data);
                    PlaceHolderElement.find('header').empty();
                    PlaceHolderElement.find('footer').empty();
                    PlaceHolderElement.find('.modal').modal('show');
                })
            })

        })
    </script>

    <!-- JS PARA TRAER LA VENTANA EMERGENTE DE CONFIRMACION DE ELIMINACION -->
    <script>
       $(function () {
            var PlaceHolderElement = $('#PlaceHolderEliminar');
            $("#btnEliminar, .btn-danger").click(function (event) {
                var id = $(this).closest('tr').find('.id').text();
                var url = $(this).data('url').replace("idCategoria", id);
                $.get(url).done(function (data) {
                    PlaceHolderElement.html(data);
                    PlaceHolderElement.find('header').empty();
                    PlaceHolderElement.find('footer').empty();
                    PlaceHolderElement.find('.modal').modal('show');
                })
            })

        })
    </script>


    <!-- JS PARA TRAER LA VENTANA EMERGENTE DE EDICION DE PRIORIDAD -->
    <script>
        $(function () {
            var PlaceHolderElement = $('#PlaceHolderEditar');
            $("#btnEditar, .btn-primary").click(function (event) {
                var id = $(this).closest('tr').find('.id').text();
                var url = $(this).data('url').replace("idCategoria", id);
                $.get(url).done(function (data) {
                    PlaceHolderElement.html(data);
                    PlaceHolderElement.find('header').empty();
                    PlaceHolderElement.find('footer').empty();
                    PlaceHolderElement.find('.modal').modal('show');
                })
            })

        })
    </script>
}


@{
        ViewData["Title"] = "Gestion Categorías";
}

<!-- DIVS CONTENEDORES DE LAS DIFERENTES VENTANAS EMERGENTES -->
<div id="PlaceHolderCategoria"></div>
<div id="PlaceHolderEliminar"></div>
<div id="PlaceHolderEditar"></div>

<!-- BOTON PARA ACCIONAR LA VENTANA EMERGENTE -->
<button id=btnAgregar type="button" class="btn btn-warning btn-sm" data-toggle="ajax-modal" data-target="#popUpAgregar" data-url="@Url.Action("VentanaAgregarCategoria")">
    Crear categoría
</button>
<br />
<br/>

<!-- INICIO DE TABLA DE DATOS -->
<table class="table">
    <tr>
        <th>
            Id
        </th>
        <th>
            Categoría
        </th>
        <th>
            Acciones
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td class="id">
                @Html.DisplayFor(i => item.id)
            </td>
            <td>
                @Html.DisplayFor(i => item.nombre)
            </td>
            <td>
                <button id=btnEditar type="button" class="btn btn-primary btn-sm" data-toggle="ajax-modal" data-target="#popUpEditar" data-url="@Url.Action("VentanaEditarCategoria","Categoria",new { id = "idCategoria" })">
                    Editar
                </button>
                <button id=btnEliminar type="button" class="btn btn-danger btn-sm" data-toggle="ajax-modal" data-target="#popUpEliminar" data-url="@Url.Action("VentanaEliminarCategoria","Categoria",new { id = "idCategoria" })">
                        Eliminar
                </button>
            </td>
        </tr>
    }

</table>

src/frontend/ServicesDeskUCAB/Views/Categoria/VentanaEditarCategoria.cshtml
@model ServicesDeskUCAB.DTO.CategoriaDTO
@section scripts{
}

@{
    ViewData["Title"] = "Gestion Categorías";
}

<!-- IMPORTACIONES DE LIBRERIAS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>


<!-- VENTANA EMERGENTE "MODAL" -->
<div class="modal fade" id="popUpEditar" tabindex="-1" role="dialog" aria-labelledby="popUpEditarTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Editar Categoría</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close" onclick="location.href='@Url.Action("GestionCategorias", "Categoria")'">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @using (Html.BeginForm("EditarCategoria", "Categoria", FormMethod.Post))
            {
                <div class="modal-body">
                    @Html.TextBoxFor(m => m.id, new { @Value = Model.id, @type="hidden"})
                    <span>Categoría: </span> @Html.TextBoxFor(m => m.nombre, new { @Value = Model.nombre})
                    @Html.ValidationMessageFor(m => m.nombre ,null, new { @class = "text-danger" })
                    <br />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="location.href='@Url.Action("GestionCategorias", "Categoria")'">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Editar</button>
                </div>
            }
        </div>
    </div>
</div>

src/frontend/ServicesDeskUCAB/Views/Categoria/VentanaEliminarCategoria.cshtml
@model int
@{
    ViewData["Title"] = "Gestion Categorías";
}

<!-- IMPORTACIONES DE LIBRERIAS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />


<!-- VENTANA EMERGENTE "MODAL" -->
<div class="modal fade" id="popUpEliminar" tabindex="-1" role="dialog" aria-labelledby="popUpEliminarTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Eliminar Categoria</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close" onclick="location.href='@Url.Action("GestionCategorias", "Categoria")'">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
                <div class="modal-body">
                    ¿Está seguro de que desea eliminar la categoría seleccionada?
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="location.href='@Url.Action("GestionCategorias", "Categoria")'">Cancelar</button>
                    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("EliminarCategoria", "Categoria",new { id = Model })'">Aceptar</button>
                </div>
        </div>
    </div>
</div>

src/frontend/ServicesDeskUCAB/Views/Categoria/ventanaAgregarCategoria.cshtml
@model ServicesDeskUCAB.DTO.CategoriaDTO
@section scripts{
}
@{
    ViewData["Title"] = "Gestion Categorías";
}
<!-- IMPORTACIONES DE LIBRERIAS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>


<!-- VENTANA EMERGENTE "MODAL" -->
<div class="modal fade" id="popUpAgregar" tabindex="-1" role="dialog" aria-labelledby="popUpAgregarTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Agregar Categoría</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close" onclick="location.href='@Url.Action("GestionCategorias", "Categoria")'">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @using (Html.BeginForm("AgregarCategoria", "Categoria", FormMethod.Post))
            {
                <div class="modal-body">
                    <span>Categoría: </span> @Html.TextBoxFor(m => m.nombre)
                    @Html.ValidationMessageFor(m => m.nombre ,null, new { @class = "text-danger" })
                    <br />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="location.href='@Url.Action("GestionCategorias", "Categoria")'">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Crear</button>
                </div>
            }
        </div>
    </div>
</div>